#!/usr/bin/env bash
set -euo pipefail

: "${WORKSPACE:=$(pwd)}"
: "${SONAR_HOST_URL:=http://localhost:9000}"
: "${SONAR_SCANNER_IMAGE:=sonarsource/sonar-scanner-cli:latest}"
: "${SONAR_USER:?SONAR_USER is required}"
: "${SONAR_PASS:?SONAR_PASS is required}"

echo "Running SAST with SonarQube..."
curl -sf "${SONAR_HOST_URL}/api/system/status" | jq -e '.status == "UP"' >/dev/null

docker run --rm \
    --network host \
    -v "${WORKSPACE}:/usr/src" \
    "${SONAR_SCANNER_IMAGE}" \
    -Dsonar.host.url="${SONAR_HOST_URL}" \
    -Dsonar.projectKey=taskflow \
    -Dsonar.projectName=TaskFlow \
    -Dsonar.sources=backend,frontend \
    -Dsonar.login="${SONAR_USER}" \
    -Dsonar.password="${SONAR_PASS}" \
    -Dsonar.exclusions=**/node_modules/**,**/build/**,**/dist/**,**/test/** \
    -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info

REPORT_TASK_FILE="${WORKSPACE}/.scannerwork/report-task.txt"
if [ ! -f "${REPORT_TASK_FILE}" ]; then
    echo "report-task.txt was not generated by Sonar scanner"
    exit 1
fi

CE_TASK_URL="$(grep '^ceTaskUrl=' "${REPORT_TASK_FILE}" | cut -d'=' -f2-)"
if [ -z "${CE_TASK_URL}" ]; then
    echo "Unable to read ceTaskUrl from report-task.txt"
    exit 1
fi

ANALYSIS_ID=""
for _ in {1..36}; do
    CE_RESPONSE="$(curl -sf -u "${SONAR_USER}:${SONAR_PASS}" "${CE_TASK_URL}")"
    CE_STATUS="$(echo "${CE_RESPONSE}" | jq -r '.task.status')"

    if [ "${CE_STATUS}" = "SUCCESS" ]; then
        ANALYSIS_ID="$(echo "${CE_RESPONSE}" | jq -r '.task.analysisId')"
        break
    fi

    if [ "${CE_STATUS}" = "FAILED" ] || [ "${CE_STATUS}" = "CANCELED" ]; then
        echo "Sonar background task failed with status ${CE_STATUS}"
        exit 1
    fi

    sleep 5
done

if [ -z "${ANALYSIS_ID}" ] || [ "${ANALYSIS_ID}" = "null" ]; then
    echo "Timed out waiting for Sonar analysis result"
    exit 1
fi

QUALITY_STATUS="$(curl -sf -u "${SONAR_USER}:${SONAR_PASS}" \
    "${SONAR_HOST_URL}/api/qualitygates/project_status?analysisId=${ANALYSIS_ID}" | \
    jq -r '.projectStatus.status')"

if [ "${QUALITY_STATUS}" != "OK" ]; then
    echo "Sonar quality gate failed: ${QUALITY_STATUS}"
    exit 1
fi
